name: 'covid19retail'
version: '1.0.0'
config-version: 2

profile: 'covid19retail'

target-path: target
test-paths: [tests]

models:
  covid19retail:
    trusted:
      +materialized: incremental
      +schema: trusted
    app:
      +materialized: table
      +schema: app
