version: "3.9"
services:
  marquez-api:
    depends_on:
      marquez-postgres:
        condition: service_healthy
    image: marquezproject/marquez:0.22.0
    links:
      - marquez-postgres:postgres
    entrypoint: ./entrypoint.sh

  marquez-web:
    depends_on:
      marquez-postgres:
        condition: service_healthy
    environment:
      - MARQUEZ_HOST=marquez-api
      - MARQUEZ_PORT=5000
    image: marquezproject/marquez-web:0.22.0
    ports:
      - 3000:3000

  marquez-postgres:
    environment:
      POSTGRES_USER: marquez
      POSTGRES_PASSWORD: marquez
      POSTGRES_DB: marquez
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "marquez"]
      interval: 5s
      retries: 5
    image: postgres:14.3-alpine
