version: "3.9"
services:
    marquez-api:
        image: marquezproject/marquez:latest
        depends_on:
            marquez-postgres:
                condition: service_healthy
        links:
            - marquez-postgres:postgres
        entrypoint: ./entrypoint.sh

    marquez-web:
        image: marquezproject/marquez-web:latest
        environment:
            - MARQUEZ_HOST=marquez-api
            - MARQUEZ_PORT=5000
        ports:
            - 3000:3000
        depends_on:
            marquez-postgres:
                condition: service_healthy

    marquez-postgres:
        environment:
            POSTGRES_USER: marquez
            POSTGRES_PASSWORD: marquez
            POSTGRES_DB: marquez
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "airflow"]
            interval: 5s
            retries: 5
        image: postgres:14.3-alpine
