version: 2

models:
  - name: fact_sales
    description: "Fact table representing liquor sales at Iowa State"
    columns:
      - name: CdSale
        tests:
          - not_null
          - unique
      - name: CdInvoice
        tests:
          - not_null
      - name: NuItemNumber
        tests:
          - not_null
      - name: CdDate
        tests:
          - not_null
      - name: CdStore
        tests:
          - not_null
      - name: CdProduct
        tests:
          - not_null

  - name: fact_events
    description: "Fact table representing Covid19 events at Iowa State"
    columns:
      - name: CdEvent
        tests:
          - not_null
          - unique
      - name: CdDate
        tests:
          - not_null
          - unique

  - name: fact_reports
    description: "Fact table representing Covid19 stats at Iowa State"
    columns:
      - name: CdReport
        tests:
          - not_null
          - unique
      - name: CdCounty
        tests:
          - not_null
      - name: CdDate
        tests:
          - not_null

  - name: dim_categories
    description: "Dimension table representing liquor product categories"
    columns:
      - name: CdCategory
        tests:
          - not_null
          - unique

  - name: dim_counties
    description: "Dimension table representing counties at Iowa State"
    columns:
      - name: CdCounty
        tests:
          - not_null
          - unique

  - name: dim_products
    description: "Dimension table representing liquor products"
    columns:
      - name: CdProduct
        tests:
          - not_null
          - unique

  - name: dim_stores
    description: "Dimension table representing liquor stores at Iowa State"
    columns:
      - name: CdStore
        tests:
          - not_null
          - unique
      - name: CdCounty
        tests:
          - not_null

  - name: dim_vendors
    description: "Dimension table representing liquor product vendors"
    columns:
      - name: CdVendor
        tests:
          - not_null
          - unique

  - name: dim_dates
    description: "Dimension table representing dates"
    columns:
      - name: CdDate
        tests:
          - not_null
          - unique
