covid19retail:
  outputs:
    dev:
      schema: covid19retail
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: covid19-retail-090522
      threads: 8
      type: bigquery
  target: prd
