version: 2

models:
  - name: covid19_open_data
    description: "An extraction from BigQuery public datasets to the ODS layer"
    columns:
      - name: date
        tests:
          - not_null
      - name: subregion1_code
        tests:
          - not_null
      - name: country_code
        tests:
          - not_null

  - name: iowa_liquor_sales
    description: "An extraction from BigQuery public datasets to the ODS layer"
    columns:
      - name: date
        tests:
          - not_null
      - name: county
        tests:
          - not_null
